version: "3.9"

services:
  triton:
    build:
      dockerfile: Triton.dockerfile
      context: .
    image: finegrained/triton-server:22.09-py3
    container_name: fg-triton
    restart: on-failure
    volumes:
      - ./models/triton:/models
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    shm_size: 2g
    command: >-
      tritonserver
      --model-repository=/models
      --strict-model-config=false
      --model-control-mode=none

  backend:
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    image: finegrained/backend:0.1
    container_name: fg-app-backend
    restart: on-failure
    environment:
      - VECTOR_STORAGE=/data/vectors
      - TRITON_HOST=triton:8001
    volumes:
      - ./data/vectors:/data/vectors
    ports:
      - 8100:8100
    depends_on:
      - triton

  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    image: finegrained/frontend:0.1
    container_name: fg-app-frontend
    restart: on-failure
    environment:
      - BACKEND_URL=http://backend:8100
      - GRADIO_DEBUG=false
    ports:
      - 8501:8501
    depends_on:
      - backend